package com.yrx.parvenu.core.pojo;

import java.util.Date;

public class IndexOverview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.id
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.index_id
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private Integer indexId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.index_code
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String indexCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.indx_sname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String indxSname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.index_ename
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String indexEname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.num
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.tclose
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String tclose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.yld_1_mon
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String yld1Mon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.base_point
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String basePoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.base_date
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private Date baseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.online_date
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private Date onlineDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.is_custom
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private Byte isCustom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.index_c_intro
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String indexCIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.index_e_intro
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String indexEIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.index_c_fullname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String indexCFullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.index_e_fullname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String indexEFullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_series
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classSeries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_eseries
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classEseries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_region
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_eregion
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classEregion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_assets
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classAssets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_eassets
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classEassets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_classify
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classClassify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_eclassify
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classEclassify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_currency
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_ecurrency
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classEcurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_hot
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.class_ehot
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private String classEhot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.insert_time
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_overview.update_time
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.id
     *
     * @return the value of index_overview.id
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.id
     *
     * @param id the value for index_overview.id
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.index_id
     *
     * @return the value of index_overview.index_id
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.index_id
     *
     * @param indexId the value for index_overview.index_id
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.index_code
     *
     * @return the value of index_overview.index_code
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getIndexCode() {
        return indexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.index_code
     *
     * @param indexCode the value for index_overview.index_code
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndexCode(String indexCode) {
        this.indexCode = indexCode == null ? null : indexCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.indx_sname
     *
     * @return the value of index_overview.indx_sname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getIndxSname() {
        return indxSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.indx_sname
     *
     * @param indxSname the value for index_overview.indx_sname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndxSname(String indxSname) {
        this.indxSname = indxSname == null ? null : indxSname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.index_ename
     *
     * @return the value of index_overview.index_ename
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getIndexEname() {
        return indexEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.index_ename
     *
     * @param indexEname the value for index_overview.index_ename
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndexEname(String indexEname) {
        this.indexEname = indexEname == null ? null : indexEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.num
     *
     * @return the value of index_overview.num
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.num
     *
     * @param num the value for index_overview.num
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.tclose
     *
     * @return the value of index_overview.tclose
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getTclose() {
        return tclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.tclose
     *
     * @param tclose the value for index_overview.tclose
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setTclose(String tclose) {
        this.tclose = tclose == null ? null : tclose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.yld_1_mon
     *
     * @return the value of index_overview.yld_1_mon
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getYld1Mon() {
        return yld1Mon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.yld_1_mon
     *
     * @param yld1Mon the value for index_overview.yld_1_mon
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setYld1Mon(String yld1Mon) {
        this.yld1Mon = yld1Mon == null ? null : yld1Mon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.base_point
     *
     * @return the value of index_overview.base_point
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getBasePoint() {
        return basePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.base_point
     *
     * @param basePoint the value for index_overview.base_point
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setBasePoint(String basePoint) {
        this.basePoint = basePoint == null ? null : basePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.base_date
     *
     * @return the value of index_overview.base_date
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Date getBaseDate() {
        return baseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.base_date
     *
     * @param baseDate the value for index_overview.base_date
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setBaseDate(Date baseDate) {
        this.baseDate = baseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.online_date
     *
     * @return the value of index_overview.online_date
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Date getOnlineDate() {
        return onlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.online_date
     *
     * @param onlineDate the value for index_overview.online_date
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setOnlineDate(Date onlineDate) {
        this.onlineDate = onlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.is_custom
     *
     * @return the value of index_overview.is_custom
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Byte getIsCustom() {
        return isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.is_custom
     *
     * @param isCustom the value for index_overview.is_custom
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIsCustom(Byte isCustom) {
        this.isCustom = isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.index_c_intro
     *
     * @return the value of index_overview.index_c_intro
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getIndexCIntro() {
        return indexCIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.index_c_intro
     *
     * @param indexCIntro the value for index_overview.index_c_intro
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndexCIntro(String indexCIntro) {
        this.indexCIntro = indexCIntro == null ? null : indexCIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.index_e_intro
     *
     * @return the value of index_overview.index_e_intro
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getIndexEIntro() {
        return indexEIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.index_e_intro
     *
     * @param indexEIntro the value for index_overview.index_e_intro
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndexEIntro(String indexEIntro) {
        this.indexEIntro = indexEIntro == null ? null : indexEIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.index_c_fullname
     *
     * @return the value of index_overview.index_c_fullname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getIndexCFullname() {
        return indexCFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.index_c_fullname
     *
     * @param indexCFullname the value for index_overview.index_c_fullname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndexCFullname(String indexCFullname) {
        this.indexCFullname = indexCFullname == null ? null : indexCFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.index_e_fullname
     *
     * @return the value of index_overview.index_e_fullname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getIndexEFullname() {
        return indexEFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.index_e_fullname
     *
     * @param indexEFullname the value for index_overview.index_e_fullname
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setIndexEFullname(String indexEFullname) {
        this.indexEFullname = indexEFullname == null ? null : indexEFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_series
     *
     * @return the value of index_overview.class_series
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassSeries() {
        return classSeries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_series
     *
     * @param classSeries the value for index_overview.class_series
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassSeries(String classSeries) {
        this.classSeries = classSeries == null ? null : classSeries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_eseries
     *
     * @return the value of index_overview.class_eseries
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassEseries() {
        return classEseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_eseries
     *
     * @param classEseries the value for index_overview.class_eseries
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassEseries(String classEseries) {
        this.classEseries = classEseries == null ? null : classEseries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_region
     *
     * @return the value of index_overview.class_region
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassRegion() {
        return classRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_region
     *
     * @param classRegion the value for index_overview.class_region
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassRegion(String classRegion) {
        this.classRegion = classRegion == null ? null : classRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_eregion
     *
     * @return the value of index_overview.class_eregion
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassEregion() {
        return classEregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_eregion
     *
     * @param classEregion the value for index_overview.class_eregion
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassEregion(String classEregion) {
        this.classEregion = classEregion == null ? null : classEregion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_assets
     *
     * @return the value of index_overview.class_assets
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassAssets() {
        return classAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_assets
     *
     * @param classAssets the value for index_overview.class_assets
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassAssets(String classAssets) {
        this.classAssets = classAssets == null ? null : classAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_eassets
     *
     * @return the value of index_overview.class_eassets
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassEassets() {
        return classEassets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_eassets
     *
     * @param classEassets the value for index_overview.class_eassets
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassEassets(String classEassets) {
        this.classEassets = classEassets == null ? null : classEassets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_classify
     *
     * @return the value of index_overview.class_classify
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassClassify() {
        return classClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_classify
     *
     * @param classClassify the value for index_overview.class_classify
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassClassify(String classClassify) {
        this.classClassify = classClassify == null ? null : classClassify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_eclassify
     *
     * @return the value of index_overview.class_eclassify
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassEclassify() {
        return classEclassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_eclassify
     *
     * @param classEclassify the value for index_overview.class_eclassify
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassEclassify(String classEclassify) {
        this.classEclassify = classEclassify == null ? null : classEclassify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_currency
     *
     * @return the value of index_overview.class_currency
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassCurrency() {
        return classCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_currency
     *
     * @param classCurrency the value for index_overview.class_currency
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassCurrency(String classCurrency) {
        this.classCurrency = classCurrency == null ? null : classCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_ecurrency
     *
     * @return the value of index_overview.class_ecurrency
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassEcurrency() {
        return classEcurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_ecurrency
     *
     * @param classEcurrency the value for index_overview.class_ecurrency
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassEcurrency(String classEcurrency) {
        this.classEcurrency = classEcurrency == null ? null : classEcurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_hot
     *
     * @return the value of index_overview.class_hot
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassHot() {
        return classHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_hot
     *
     * @param classHot the value for index_overview.class_hot
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassHot(String classHot) {
        this.classHot = classHot == null ? null : classHot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.class_ehot
     *
     * @return the value of index_overview.class_ehot
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getClassEhot() {
        return classEhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.class_ehot
     *
     * @param classEhot the value for index_overview.class_ehot
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setClassEhot(String classEhot) {
        this.classEhot = classEhot == null ? null : classEhot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.insert_time
     *
     * @return the value of index_overview.insert_time
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.insert_time
     *
     * @param insertTime the value for index_overview.insert_time
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_overview.update_time
     *
     * @return the value of index_overview.update_time
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_overview.update_time
     *
     * @param updateTime the value for index_overview.update_time
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}