package com.yrx.parvenu.core.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IndexOverviewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public IndexOverviewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIndexIdIsNull() {
            addCriterion("index_id is null");
            return (Criteria) this;
        }

        public Criteria andIndexIdIsNotNull() {
            addCriterion("index_id is not null");
            return (Criteria) this;
        }

        public Criteria andIndexIdEqualTo(Integer value) {
            addCriterion("index_id =", value, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdNotEqualTo(Integer value) {
            addCriterion("index_id <>", value, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdGreaterThan(Integer value) {
            addCriterion("index_id >", value, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("index_id >=", value, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdLessThan(Integer value) {
            addCriterion("index_id <", value, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdLessThanOrEqualTo(Integer value) {
            addCriterion("index_id <=", value, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdIn(List<Integer> values) {
            addCriterion("index_id in", values, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdNotIn(List<Integer> values) {
            addCriterion("index_id not in", values, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdBetween(Integer value1, Integer value2) {
            addCriterion("index_id between", value1, value2, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexIdNotBetween(Integer value1, Integer value2) {
            addCriterion("index_id not between", value1, value2, "indexId");
            return (Criteria) this;
        }

        public Criteria andIndexCodeIsNull() {
            addCriterion("index_code is null");
            return (Criteria) this;
        }

        public Criteria andIndexCodeIsNotNull() {
            addCriterion("index_code is not null");
            return (Criteria) this;
        }

        public Criteria andIndexCodeEqualTo(String value) {
            addCriterion("index_code =", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotEqualTo(String value) {
            addCriterion("index_code <>", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeGreaterThan(String value) {
            addCriterion("index_code >", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeGreaterThanOrEqualTo(String value) {
            addCriterion("index_code >=", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeLessThan(String value) {
            addCriterion("index_code <", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeLessThanOrEqualTo(String value) {
            addCriterion("index_code <=", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeLike(String value) {
            addCriterion("index_code like", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotLike(String value) {
            addCriterion("index_code not like", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeIn(List<String> values) {
            addCriterion("index_code in", values, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotIn(List<String> values) {
            addCriterion("index_code not in", values, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeBetween(String value1, String value2) {
            addCriterion("index_code between", value1, value2, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotBetween(String value1, String value2) {
            addCriterion("index_code not between", value1, value2, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndxSnameIsNull() {
            addCriterion("indx_sname is null");
            return (Criteria) this;
        }

        public Criteria andIndxSnameIsNotNull() {
            addCriterion("indx_sname is not null");
            return (Criteria) this;
        }

        public Criteria andIndxSnameEqualTo(String value) {
            addCriterion("indx_sname =", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameNotEqualTo(String value) {
            addCriterion("indx_sname <>", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameGreaterThan(String value) {
            addCriterion("indx_sname >", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameGreaterThanOrEqualTo(String value) {
            addCriterion("indx_sname >=", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameLessThan(String value) {
            addCriterion("indx_sname <", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameLessThanOrEqualTo(String value) {
            addCriterion("indx_sname <=", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameLike(String value) {
            addCriterion("indx_sname like", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameNotLike(String value) {
            addCriterion("indx_sname not like", value, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameIn(List<String> values) {
            addCriterion("indx_sname in", values, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameNotIn(List<String> values) {
            addCriterion("indx_sname not in", values, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameBetween(String value1, String value2) {
            addCriterion("indx_sname between", value1, value2, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndxSnameNotBetween(String value1, String value2) {
            addCriterion("indx_sname not between", value1, value2, "indxSname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameIsNull() {
            addCriterion("index_ename is null");
            return (Criteria) this;
        }

        public Criteria andIndexEnameIsNotNull() {
            addCriterion("index_ename is not null");
            return (Criteria) this;
        }

        public Criteria andIndexEnameEqualTo(String value) {
            addCriterion("index_ename =", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameNotEqualTo(String value) {
            addCriterion("index_ename <>", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameGreaterThan(String value) {
            addCriterion("index_ename >", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameGreaterThanOrEqualTo(String value) {
            addCriterion("index_ename >=", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameLessThan(String value) {
            addCriterion("index_ename <", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameLessThanOrEqualTo(String value) {
            addCriterion("index_ename <=", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameLike(String value) {
            addCriterion("index_ename like", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameNotLike(String value) {
            addCriterion("index_ename not like", value, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameIn(List<String> values) {
            addCriterion("index_ename in", values, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameNotIn(List<String> values) {
            addCriterion("index_ename not in", values, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameBetween(String value1, String value2) {
            addCriterion("index_ename between", value1, value2, "indexEname");
            return (Criteria) this;
        }

        public Criteria andIndexEnameNotBetween(String value1, String value2) {
            addCriterion("index_ename not between", value1, value2, "indexEname");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andTcloseIsNull() {
            addCriterion("tclose is null");
            return (Criteria) this;
        }

        public Criteria andTcloseIsNotNull() {
            addCriterion("tclose is not null");
            return (Criteria) this;
        }

        public Criteria andTcloseEqualTo(String value) {
            addCriterion("tclose =", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseNotEqualTo(String value) {
            addCriterion("tclose <>", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseGreaterThan(String value) {
            addCriterion("tclose >", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseGreaterThanOrEqualTo(String value) {
            addCriterion("tclose >=", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseLessThan(String value) {
            addCriterion("tclose <", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseLessThanOrEqualTo(String value) {
            addCriterion("tclose <=", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseLike(String value) {
            addCriterion("tclose like", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseNotLike(String value) {
            addCriterion("tclose not like", value, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseIn(List<String> values) {
            addCriterion("tclose in", values, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseNotIn(List<String> values) {
            addCriterion("tclose not in", values, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseBetween(String value1, String value2) {
            addCriterion("tclose between", value1, value2, "tclose");
            return (Criteria) this;
        }

        public Criteria andTcloseNotBetween(String value1, String value2) {
            addCriterion("tclose not between", value1, value2, "tclose");
            return (Criteria) this;
        }

        public Criteria andYld1MonIsNull() {
            addCriterion("yld_1_mon is null");
            return (Criteria) this;
        }

        public Criteria andYld1MonIsNotNull() {
            addCriterion("yld_1_mon is not null");
            return (Criteria) this;
        }

        public Criteria andYld1MonEqualTo(String value) {
            addCriterion("yld_1_mon =", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonNotEqualTo(String value) {
            addCriterion("yld_1_mon <>", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonGreaterThan(String value) {
            addCriterion("yld_1_mon >", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonGreaterThanOrEqualTo(String value) {
            addCriterion("yld_1_mon >=", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonLessThan(String value) {
            addCriterion("yld_1_mon <", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonLessThanOrEqualTo(String value) {
            addCriterion("yld_1_mon <=", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonLike(String value) {
            addCriterion("yld_1_mon like", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonNotLike(String value) {
            addCriterion("yld_1_mon not like", value, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonIn(List<String> values) {
            addCriterion("yld_1_mon in", values, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonNotIn(List<String> values) {
            addCriterion("yld_1_mon not in", values, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonBetween(String value1, String value2) {
            addCriterion("yld_1_mon between", value1, value2, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andYld1MonNotBetween(String value1, String value2) {
            addCriterion("yld_1_mon not between", value1, value2, "yld1Mon");
            return (Criteria) this;
        }

        public Criteria andBasePointIsNull() {
            addCriterion("base_point is null");
            return (Criteria) this;
        }

        public Criteria andBasePointIsNotNull() {
            addCriterion("base_point is not null");
            return (Criteria) this;
        }

        public Criteria andBasePointEqualTo(String value) {
            addCriterion("base_point =", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointNotEqualTo(String value) {
            addCriterion("base_point <>", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointGreaterThan(String value) {
            addCriterion("base_point >", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointGreaterThanOrEqualTo(String value) {
            addCriterion("base_point >=", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointLessThan(String value) {
            addCriterion("base_point <", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointLessThanOrEqualTo(String value) {
            addCriterion("base_point <=", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointLike(String value) {
            addCriterion("base_point like", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointNotLike(String value) {
            addCriterion("base_point not like", value, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointIn(List<String> values) {
            addCriterion("base_point in", values, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointNotIn(List<String> values) {
            addCriterion("base_point not in", values, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointBetween(String value1, String value2) {
            addCriterion("base_point between", value1, value2, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBasePointNotBetween(String value1, String value2) {
            addCriterion("base_point not between", value1, value2, "basePoint");
            return (Criteria) this;
        }

        public Criteria andBaseDateIsNull() {
            addCriterion("base_date is null");
            return (Criteria) this;
        }

        public Criteria andBaseDateIsNotNull() {
            addCriterion("base_date is not null");
            return (Criteria) this;
        }

        public Criteria andBaseDateEqualTo(Date value) {
            addCriterion("base_date =", value, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateNotEqualTo(Date value) {
            addCriterion("base_date <>", value, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateGreaterThan(Date value) {
            addCriterion("base_date >", value, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("base_date >=", value, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateLessThan(Date value) {
            addCriterion("base_date <", value, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateLessThanOrEqualTo(Date value) {
            addCriterion("base_date <=", value, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateIn(List<Date> values) {
            addCriterion("base_date in", values, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateNotIn(List<Date> values) {
            addCriterion("base_date not in", values, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateBetween(Date value1, Date value2) {
            addCriterion("base_date between", value1, value2, "baseDate");
            return (Criteria) this;
        }

        public Criteria andBaseDateNotBetween(Date value1, Date value2) {
            addCriterion("base_date not between", value1, value2, "baseDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIsNull() {
            addCriterion("online_date is null");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIsNotNull() {
            addCriterion("online_date is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineDateEqualTo(Date value) {
            addCriterion("online_date =", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotEqualTo(Date value) {
            addCriterion("online_date <>", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateGreaterThan(Date value) {
            addCriterion("online_date >", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateGreaterThanOrEqualTo(Date value) {
            addCriterion("online_date >=", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateLessThan(Date value) {
            addCriterion("online_date <", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateLessThanOrEqualTo(Date value) {
            addCriterion("online_date <=", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIn(List<Date> values) {
            addCriterion("online_date in", values, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotIn(List<Date> values) {
            addCriterion("online_date not in", values, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateBetween(Date value1, Date value2) {
            addCriterion("online_date between", value1, value2, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotBetween(Date value1, Date value2) {
            addCriterion("online_date not between", value1, value2, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andIsCustomIsNull() {
            addCriterion("is_custom is null");
            return (Criteria) this;
        }

        public Criteria andIsCustomIsNotNull() {
            addCriterion("is_custom is not null");
            return (Criteria) this;
        }

        public Criteria andIsCustomEqualTo(Byte value) {
            addCriterion("is_custom =", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotEqualTo(Byte value) {
            addCriterion("is_custom <>", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomGreaterThan(Byte value) {
            addCriterion("is_custom >", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_custom >=", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomLessThan(Byte value) {
            addCriterion("is_custom <", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomLessThanOrEqualTo(Byte value) {
            addCriterion("is_custom <=", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomIn(List<Byte> values) {
            addCriterion("is_custom in", values, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotIn(List<Byte> values) {
            addCriterion("is_custom not in", values, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomBetween(Byte value1, Byte value2) {
            addCriterion("is_custom between", value1, value2, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotBetween(Byte value1, Byte value2) {
            addCriterion("is_custom not between", value1, value2, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroIsNull() {
            addCriterion("index_c_intro is null");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroIsNotNull() {
            addCriterion("index_c_intro is not null");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroEqualTo(String value) {
            addCriterion("index_c_intro =", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroNotEqualTo(String value) {
            addCriterion("index_c_intro <>", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroGreaterThan(String value) {
            addCriterion("index_c_intro >", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroGreaterThanOrEqualTo(String value) {
            addCriterion("index_c_intro >=", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroLessThan(String value) {
            addCriterion("index_c_intro <", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroLessThanOrEqualTo(String value) {
            addCriterion("index_c_intro <=", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroLike(String value) {
            addCriterion("index_c_intro like", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroNotLike(String value) {
            addCriterion("index_c_intro not like", value, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroIn(List<String> values) {
            addCriterion("index_c_intro in", values, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroNotIn(List<String> values) {
            addCriterion("index_c_intro not in", values, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroBetween(String value1, String value2) {
            addCriterion("index_c_intro between", value1, value2, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCIntroNotBetween(String value1, String value2) {
            addCriterion("index_c_intro not between", value1, value2, "indexCIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroIsNull() {
            addCriterion("index_e_intro is null");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroIsNotNull() {
            addCriterion("index_e_intro is not null");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroEqualTo(String value) {
            addCriterion("index_e_intro =", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroNotEqualTo(String value) {
            addCriterion("index_e_intro <>", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroGreaterThan(String value) {
            addCriterion("index_e_intro >", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroGreaterThanOrEqualTo(String value) {
            addCriterion("index_e_intro >=", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroLessThan(String value) {
            addCriterion("index_e_intro <", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroLessThanOrEqualTo(String value) {
            addCriterion("index_e_intro <=", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroLike(String value) {
            addCriterion("index_e_intro like", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroNotLike(String value) {
            addCriterion("index_e_intro not like", value, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroIn(List<String> values) {
            addCriterion("index_e_intro in", values, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroNotIn(List<String> values) {
            addCriterion("index_e_intro not in", values, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroBetween(String value1, String value2) {
            addCriterion("index_e_intro between", value1, value2, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexEIntroNotBetween(String value1, String value2) {
            addCriterion("index_e_intro not between", value1, value2, "indexEIntro");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameIsNull() {
            addCriterion("index_c_fullname is null");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameIsNotNull() {
            addCriterion("index_c_fullname is not null");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameEqualTo(String value) {
            addCriterion("index_c_fullname =", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameNotEqualTo(String value) {
            addCriterion("index_c_fullname <>", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameGreaterThan(String value) {
            addCriterion("index_c_fullname >", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameGreaterThanOrEqualTo(String value) {
            addCriterion("index_c_fullname >=", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameLessThan(String value) {
            addCriterion("index_c_fullname <", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameLessThanOrEqualTo(String value) {
            addCriterion("index_c_fullname <=", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameLike(String value) {
            addCriterion("index_c_fullname like", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameNotLike(String value) {
            addCriterion("index_c_fullname not like", value, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameIn(List<String> values) {
            addCriterion("index_c_fullname in", values, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameNotIn(List<String> values) {
            addCriterion("index_c_fullname not in", values, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameBetween(String value1, String value2) {
            addCriterion("index_c_fullname between", value1, value2, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexCFullnameNotBetween(String value1, String value2) {
            addCriterion("index_c_fullname not between", value1, value2, "indexCFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameIsNull() {
            addCriterion("index_e_fullname is null");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameIsNotNull() {
            addCriterion("index_e_fullname is not null");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameEqualTo(String value) {
            addCriterion("index_e_fullname =", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameNotEqualTo(String value) {
            addCriterion("index_e_fullname <>", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameGreaterThan(String value) {
            addCriterion("index_e_fullname >", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameGreaterThanOrEqualTo(String value) {
            addCriterion("index_e_fullname >=", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameLessThan(String value) {
            addCriterion("index_e_fullname <", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameLessThanOrEqualTo(String value) {
            addCriterion("index_e_fullname <=", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameLike(String value) {
            addCriterion("index_e_fullname like", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameNotLike(String value) {
            addCriterion("index_e_fullname not like", value, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameIn(List<String> values) {
            addCriterion("index_e_fullname in", values, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameNotIn(List<String> values) {
            addCriterion("index_e_fullname not in", values, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameBetween(String value1, String value2) {
            addCriterion("index_e_fullname between", value1, value2, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andIndexEFullnameNotBetween(String value1, String value2) {
            addCriterion("index_e_fullname not between", value1, value2, "indexEFullname");
            return (Criteria) this;
        }

        public Criteria andClassSeriesIsNull() {
            addCriterion("class_series is null");
            return (Criteria) this;
        }

        public Criteria andClassSeriesIsNotNull() {
            addCriterion("class_series is not null");
            return (Criteria) this;
        }

        public Criteria andClassSeriesEqualTo(String value) {
            addCriterion("class_series =", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesNotEqualTo(String value) {
            addCriterion("class_series <>", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesGreaterThan(String value) {
            addCriterion("class_series >", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesGreaterThanOrEqualTo(String value) {
            addCriterion("class_series >=", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesLessThan(String value) {
            addCriterion("class_series <", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesLessThanOrEqualTo(String value) {
            addCriterion("class_series <=", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesLike(String value) {
            addCriterion("class_series like", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesNotLike(String value) {
            addCriterion("class_series not like", value, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesIn(List<String> values) {
            addCriterion("class_series in", values, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesNotIn(List<String> values) {
            addCriterion("class_series not in", values, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesBetween(String value1, String value2) {
            addCriterion("class_series between", value1, value2, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassSeriesNotBetween(String value1, String value2) {
            addCriterion("class_series not between", value1, value2, "classSeries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesIsNull() {
            addCriterion("class_eseries is null");
            return (Criteria) this;
        }

        public Criteria andClassEseriesIsNotNull() {
            addCriterion("class_eseries is not null");
            return (Criteria) this;
        }

        public Criteria andClassEseriesEqualTo(String value) {
            addCriterion("class_eseries =", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesNotEqualTo(String value) {
            addCriterion("class_eseries <>", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesGreaterThan(String value) {
            addCriterion("class_eseries >", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesGreaterThanOrEqualTo(String value) {
            addCriterion("class_eseries >=", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesLessThan(String value) {
            addCriterion("class_eseries <", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesLessThanOrEqualTo(String value) {
            addCriterion("class_eseries <=", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesLike(String value) {
            addCriterion("class_eseries like", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesNotLike(String value) {
            addCriterion("class_eseries not like", value, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesIn(List<String> values) {
            addCriterion("class_eseries in", values, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesNotIn(List<String> values) {
            addCriterion("class_eseries not in", values, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesBetween(String value1, String value2) {
            addCriterion("class_eseries between", value1, value2, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassEseriesNotBetween(String value1, String value2) {
            addCriterion("class_eseries not between", value1, value2, "classEseries");
            return (Criteria) this;
        }

        public Criteria andClassRegionIsNull() {
            addCriterion("class_region is null");
            return (Criteria) this;
        }

        public Criteria andClassRegionIsNotNull() {
            addCriterion("class_region is not null");
            return (Criteria) this;
        }

        public Criteria andClassRegionEqualTo(String value) {
            addCriterion("class_region =", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionNotEqualTo(String value) {
            addCriterion("class_region <>", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionGreaterThan(String value) {
            addCriterion("class_region >", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionGreaterThanOrEqualTo(String value) {
            addCriterion("class_region >=", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionLessThan(String value) {
            addCriterion("class_region <", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionLessThanOrEqualTo(String value) {
            addCriterion("class_region <=", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionLike(String value) {
            addCriterion("class_region like", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionNotLike(String value) {
            addCriterion("class_region not like", value, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionIn(List<String> values) {
            addCriterion("class_region in", values, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionNotIn(List<String> values) {
            addCriterion("class_region not in", values, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionBetween(String value1, String value2) {
            addCriterion("class_region between", value1, value2, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassRegionNotBetween(String value1, String value2) {
            addCriterion("class_region not between", value1, value2, "classRegion");
            return (Criteria) this;
        }

        public Criteria andClassEregionIsNull() {
            addCriterion("class_eregion is null");
            return (Criteria) this;
        }

        public Criteria andClassEregionIsNotNull() {
            addCriterion("class_eregion is not null");
            return (Criteria) this;
        }

        public Criteria andClassEregionEqualTo(String value) {
            addCriterion("class_eregion =", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionNotEqualTo(String value) {
            addCriterion("class_eregion <>", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionGreaterThan(String value) {
            addCriterion("class_eregion >", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionGreaterThanOrEqualTo(String value) {
            addCriterion("class_eregion >=", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionLessThan(String value) {
            addCriterion("class_eregion <", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionLessThanOrEqualTo(String value) {
            addCriterion("class_eregion <=", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionLike(String value) {
            addCriterion("class_eregion like", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionNotLike(String value) {
            addCriterion("class_eregion not like", value, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionIn(List<String> values) {
            addCriterion("class_eregion in", values, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionNotIn(List<String> values) {
            addCriterion("class_eregion not in", values, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionBetween(String value1, String value2) {
            addCriterion("class_eregion between", value1, value2, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassEregionNotBetween(String value1, String value2) {
            addCriterion("class_eregion not between", value1, value2, "classEregion");
            return (Criteria) this;
        }

        public Criteria andClassAssetsIsNull() {
            addCriterion("class_assets is null");
            return (Criteria) this;
        }

        public Criteria andClassAssetsIsNotNull() {
            addCriterion("class_assets is not null");
            return (Criteria) this;
        }

        public Criteria andClassAssetsEqualTo(String value) {
            addCriterion("class_assets =", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsNotEqualTo(String value) {
            addCriterion("class_assets <>", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsGreaterThan(String value) {
            addCriterion("class_assets >", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsGreaterThanOrEqualTo(String value) {
            addCriterion("class_assets >=", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsLessThan(String value) {
            addCriterion("class_assets <", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsLessThanOrEqualTo(String value) {
            addCriterion("class_assets <=", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsLike(String value) {
            addCriterion("class_assets like", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsNotLike(String value) {
            addCriterion("class_assets not like", value, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsIn(List<String> values) {
            addCriterion("class_assets in", values, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsNotIn(List<String> values) {
            addCriterion("class_assets not in", values, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsBetween(String value1, String value2) {
            addCriterion("class_assets between", value1, value2, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassAssetsNotBetween(String value1, String value2) {
            addCriterion("class_assets not between", value1, value2, "classAssets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsIsNull() {
            addCriterion("class_eassets is null");
            return (Criteria) this;
        }

        public Criteria andClassEassetsIsNotNull() {
            addCriterion("class_eassets is not null");
            return (Criteria) this;
        }

        public Criteria andClassEassetsEqualTo(String value) {
            addCriterion("class_eassets =", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsNotEqualTo(String value) {
            addCriterion("class_eassets <>", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsGreaterThan(String value) {
            addCriterion("class_eassets >", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsGreaterThanOrEqualTo(String value) {
            addCriterion("class_eassets >=", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsLessThan(String value) {
            addCriterion("class_eassets <", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsLessThanOrEqualTo(String value) {
            addCriterion("class_eassets <=", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsLike(String value) {
            addCriterion("class_eassets like", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsNotLike(String value) {
            addCriterion("class_eassets not like", value, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsIn(List<String> values) {
            addCriterion("class_eassets in", values, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsNotIn(List<String> values) {
            addCriterion("class_eassets not in", values, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsBetween(String value1, String value2) {
            addCriterion("class_eassets between", value1, value2, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassEassetsNotBetween(String value1, String value2) {
            addCriterion("class_eassets not between", value1, value2, "classEassets");
            return (Criteria) this;
        }

        public Criteria andClassClassifyIsNull() {
            addCriterion("class_classify is null");
            return (Criteria) this;
        }

        public Criteria andClassClassifyIsNotNull() {
            addCriterion("class_classify is not null");
            return (Criteria) this;
        }

        public Criteria andClassClassifyEqualTo(String value) {
            addCriterion("class_classify =", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyNotEqualTo(String value) {
            addCriterion("class_classify <>", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyGreaterThan(String value) {
            addCriterion("class_classify >", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyGreaterThanOrEqualTo(String value) {
            addCriterion("class_classify >=", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyLessThan(String value) {
            addCriterion("class_classify <", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyLessThanOrEqualTo(String value) {
            addCriterion("class_classify <=", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyLike(String value) {
            addCriterion("class_classify like", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyNotLike(String value) {
            addCriterion("class_classify not like", value, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyIn(List<String> values) {
            addCriterion("class_classify in", values, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyNotIn(List<String> values) {
            addCriterion("class_classify not in", values, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyBetween(String value1, String value2) {
            addCriterion("class_classify between", value1, value2, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassClassifyNotBetween(String value1, String value2) {
            addCriterion("class_classify not between", value1, value2, "classClassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyIsNull() {
            addCriterion("class_eclassify is null");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyIsNotNull() {
            addCriterion("class_eclassify is not null");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyEqualTo(String value) {
            addCriterion("class_eclassify =", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyNotEqualTo(String value) {
            addCriterion("class_eclassify <>", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyGreaterThan(String value) {
            addCriterion("class_eclassify >", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyGreaterThanOrEqualTo(String value) {
            addCriterion("class_eclassify >=", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyLessThan(String value) {
            addCriterion("class_eclassify <", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyLessThanOrEqualTo(String value) {
            addCriterion("class_eclassify <=", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyLike(String value) {
            addCriterion("class_eclassify like", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyNotLike(String value) {
            addCriterion("class_eclassify not like", value, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyIn(List<String> values) {
            addCriterion("class_eclassify in", values, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyNotIn(List<String> values) {
            addCriterion("class_eclassify not in", values, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyBetween(String value1, String value2) {
            addCriterion("class_eclassify between", value1, value2, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassEclassifyNotBetween(String value1, String value2) {
            addCriterion("class_eclassify not between", value1, value2, "classEclassify");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyIsNull() {
            addCriterion("class_currency is null");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyIsNotNull() {
            addCriterion("class_currency is not null");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyEqualTo(String value) {
            addCriterion("class_currency =", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyNotEqualTo(String value) {
            addCriterion("class_currency <>", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyGreaterThan(String value) {
            addCriterion("class_currency >", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("class_currency >=", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyLessThan(String value) {
            addCriterion("class_currency <", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyLessThanOrEqualTo(String value) {
            addCriterion("class_currency <=", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyLike(String value) {
            addCriterion("class_currency like", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyNotLike(String value) {
            addCriterion("class_currency not like", value, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyIn(List<String> values) {
            addCriterion("class_currency in", values, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyNotIn(List<String> values) {
            addCriterion("class_currency not in", values, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyBetween(String value1, String value2) {
            addCriterion("class_currency between", value1, value2, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassCurrencyNotBetween(String value1, String value2) {
            addCriterion("class_currency not between", value1, value2, "classCurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyIsNull() {
            addCriterion("class_ecurrency is null");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyIsNotNull() {
            addCriterion("class_ecurrency is not null");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyEqualTo(String value) {
            addCriterion("class_ecurrency =", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyNotEqualTo(String value) {
            addCriterion("class_ecurrency <>", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyGreaterThan(String value) {
            addCriterion("class_ecurrency >", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("class_ecurrency >=", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyLessThan(String value) {
            addCriterion("class_ecurrency <", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyLessThanOrEqualTo(String value) {
            addCriterion("class_ecurrency <=", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyLike(String value) {
            addCriterion("class_ecurrency like", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyNotLike(String value) {
            addCriterion("class_ecurrency not like", value, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyIn(List<String> values) {
            addCriterion("class_ecurrency in", values, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyNotIn(List<String> values) {
            addCriterion("class_ecurrency not in", values, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyBetween(String value1, String value2) {
            addCriterion("class_ecurrency between", value1, value2, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassEcurrencyNotBetween(String value1, String value2) {
            addCriterion("class_ecurrency not between", value1, value2, "classEcurrency");
            return (Criteria) this;
        }

        public Criteria andClassHotIsNull() {
            addCriterion("class_hot is null");
            return (Criteria) this;
        }

        public Criteria andClassHotIsNotNull() {
            addCriterion("class_hot is not null");
            return (Criteria) this;
        }

        public Criteria andClassHotEqualTo(String value) {
            addCriterion("class_hot =", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotNotEqualTo(String value) {
            addCriterion("class_hot <>", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotGreaterThan(String value) {
            addCriterion("class_hot >", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotGreaterThanOrEqualTo(String value) {
            addCriterion("class_hot >=", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotLessThan(String value) {
            addCriterion("class_hot <", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotLessThanOrEqualTo(String value) {
            addCriterion("class_hot <=", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotLike(String value) {
            addCriterion("class_hot like", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotNotLike(String value) {
            addCriterion("class_hot not like", value, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotIn(List<String> values) {
            addCriterion("class_hot in", values, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotNotIn(List<String> values) {
            addCriterion("class_hot not in", values, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotBetween(String value1, String value2) {
            addCriterion("class_hot between", value1, value2, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassHotNotBetween(String value1, String value2) {
            addCriterion("class_hot not between", value1, value2, "classHot");
            return (Criteria) this;
        }

        public Criteria andClassEhotIsNull() {
            addCriterion("class_ehot is null");
            return (Criteria) this;
        }

        public Criteria andClassEhotIsNotNull() {
            addCriterion("class_ehot is not null");
            return (Criteria) this;
        }

        public Criteria andClassEhotEqualTo(String value) {
            addCriterion("class_ehot =", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotNotEqualTo(String value) {
            addCriterion("class_ehot <>", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotGreaterThan(String value) {
            addCriterion("class_ehot >", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotGreaterThanOrEqualTo(String value) {
            addCriterion("class_ehot >=", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotLessThan(String value) {
            addCriterion("class_ehot <", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotLessThanOrEqualTo(String value) {
            addCriterion("class_ehot <=", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotLike(String value) {
            addCriterion("class_ehot like", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotNotLike(String value) {
            addCriterion("class_ehot not like", value, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotIn(List<String> values) {
            addCriterion("class_ehot in", values, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotNotIn(List<String> values) {
            addCriterion("class_ehot not in", values, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotBetween(String value1, String value2) {
            addCriterion("class_ehot between", value1, value2, "classEhot");
            return (Criteria) this;
        }

        public Criteria andClassEhotNotBetween(String value1, String value2) {
            addCriterion("class_ehot not between", value1, value2, "classEhot");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNull() {
            addCriterion("insert_time is null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNotNull() {
            addCriterion("insert_time is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeEqualTo(Date value) {
            addCriterion("insert_time =", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotEqualTo(Date value) {
            addCriterion("insert_time <>", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThan(Date value) {
            addCriterion("insert_time >", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_time >=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThan(Date value) {
            addCriterion("insert_time <", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThanOrEqualTo(Date value) {
            addCriterion("insert_time <=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIn(List<Date> values) {
            addCriterion("insert_time in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotIn(List<Date> values) {
            addCriterion("insert_time not in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeBetween(Date value1, Date value2) {
            addCriterion("insert_time between", value1, value2, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotBetween(Date value1, Date value2) {
            addCriterion("insert_time not between", value1, value2, "insertTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table index_overview
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 20 16:19:53 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table index_overview
     *
     * @mbg.generated Thu Feb 20 16:19:53 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}